# docker compose file for Rakovku Telegram Bot.
# Replace "your_bot_token" with the token received from @botfather.

version: "3"

services:
  bot:
    build: .
    environment:
      - RAKOVKU_BOT_TOKEN=your_bot_token_here # Replace with the actual Telegram bot token
